"""modified orders and added an association table with orders and items to store user orders

Revision ID: 033407ddcbce
Revises: ff44b54abf83
Create Date: 2026-07-29 11:52:59.823514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '033407ddcbce'
down_revision: Union[str, Sequence[str], None] = 'ff44b54abf83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_item_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'Quantity')
    op.drop_column('orders', 'item_id')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('Quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orders_item_id_fkey'), 'orders', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
