"""added deleted at field

Revision ID: 085fc262e791
Revises: b5b4f355a1b0
Create Date: 2026-07-20 16:11:07.267707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '085fc262e791'
down_revision: Union[str, Sequence[str], None] = 'b5b4f355a1b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'deleted at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###
