"""updated tables with createdAt with default correctly

Revision ID: 21728ec56fe1
Revises: e4acd11fe7a4
Create Date: 2026-07-20 12:10:34.502689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21728ec56fe1'
down_revision: Union[str, Sequence[str], None] = 'e4acd11fe7a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
