"""updated tables with createdAt

Revision ID: 465ae161c4fa
Revises: 694a3cacf2a4
Create Date: 2026-07-20 10:18:13.039016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '465ae161c4fa'
down_revision: Union[str, Sequence[str], None] = '694a3cacf2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('categories', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('items', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    op.add_column('items', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('items', 'CreatedAt')
    op.drop_column('items', 'UdatedAt')
    op.alter_column('news', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('reviews', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.add_column('wishlist', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    op.add_column('wishlist', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('wishlist', 'CreatedAt')
    op.drop_column('wishlist', 'UpdatedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('UpdatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('wishlist', sa.Column('CreatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('wishlist', 'updated_at')
    op.drop_column('wishlist', 'created_at')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('reviews', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('news', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.add_column('items', sa.Column('UdatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('CreatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('items', 'updated_at')
    op.drop_column('items', 'created_at')
    op.alter_column('categories', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('address', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
