"""updated tables to be better

Revision ID: 56cb6db0d612
Revises: 55c5219d24f2
Create Date: 2026-07-29 17:09:39.820548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56cb6db0d612'
down_revision: Union[str, Sequence[str], None] = '55c5219d24f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(length=8), nullable=True))
    op.add_column('orders', sa.Column('TimeStamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'TimeStamp')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
