"""added 'primary key' to 'item_id' in 'order_items' mapping table

Revision ID: 7b336cfba30e
Revises: b9505f2c242f
Create Date: 2026-08-04 14:27:16.286902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b336cfba30e'
down_revision: Union[str, Sequence[str], None] = 'b9505f2c242f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
