"""added 'deleted_at' for items and forieng keys

Revision ID: ac4fc3e5f025
Revises: 085fc262e791
Create Date: 2026-07-21 11:11:48.458706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4fc3e5f025'
down_revision: Union[str, Sequence[str], None] = '085fc262e791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address', 'users', ['user_id'], ['id'])
    op.add_column('billigInformation', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'billigInformation', 'users', ['user_id'], ['id'])
    op.add_column('items', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('news', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'items', ['item_id'], ['id'])
    op.add_column('payment_system', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payment_system', 'users', ['user_id'], ['id'])
    op.add_column('reviews', sa.Column('item_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'items', ['item_id'], ['id'])
    op.add_column('wishlist', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('wishlist', sa.Column('itemLis_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wishlist', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'wishlist', 'itemList', ['itemLis_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.drop_column('wishlist', 'itemLis_id')
    op.drop_column('wishlist', 'user_id')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'deleted_at')
    op.drop_column('reviews', 'user_id')
    op.drop_column('reviews', 'item_id')
    op.drop_constraint(None, 'payment_system', type_='foreignkey')
    op.drop_column('payment_system', 'user_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'item_id')
    op.drop_column('orders', 'user_id')
    op.drop_column('news', 'deleted_at')
    op.drop_column('items', 'deleted_at')
    op.drop_constraint(None, 'billigInformation', type_='foreignkey')
    op.drop_column('billigInformation', 'user_id')
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'user_id')
    # ### end Alembic commands ###
