"""changed category in items to be foreign key to categories

Revision ID: ff44b54abf83
Revises: ac4fc3e5f025
Create Date: 2026-07-22 15:30:53.027573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff44b54abf83'
down_revision: Union[str, Sequence[str], None] = 'ac4fc3e5f025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('categories', 'item_Id')
    op.create_foreign_key(None, 'itemList', 'items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'itemList', type_='foreignkey')
    op.add_column('categories', sa.Column('item_Id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'deleted_at')
    op.drop_table('items')
    # ### end Alembic commands ###
